In [9]:
a=10
b=52
print(b)
a

52


10

In [10]:
import numpy as np


In [11]:
l=[456,56,10,56]
type(l)

list

In [13]:
j=np.array(l)
j.ndim
j


array([456,  56,  10,  56])

In [14]:
k= np.array([[45,56,63],[78,96,31]])
k.ndim


2

In [19]:
print(k)
k[1][-1]

[[45 56 63]
 [78 96 31]]


np.int64(31)